services:
  - type: web
    name: udinex-sentinel
    runtime: static
    repo: https://github.com/ass12222/udinex-sentinel
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_HELIUS_KEY
        value: 151a78e1-7320-448d-8bd7-e6467526c8be
      - key: VITE_API_URL
        value: https://udinex-sentinel-api.onrender.com

  - type: web
    name: udinex-sentinel-api
    runtime: node
    repo: https://github.com/ass12222/udinex-sentinel
    buildCommand: cd server && npm install
    startCommand: cd server && npx tsx src/index.ts
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: da-incollare-dalla-dashboard
      - key: TELEGRAM_CHAT_IDS
        value: "7639968217"
